config/routes.rb
Rails.application.routes.draw do
  resources :competitions
  resources :games
  resources :players
  resources :teams
  get 'guests/new'
  resources :participants
  resources :guests
  resources :attendance
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'basic-qr-code-reader', to: 'basic_qr_codes#index'
  post 'attendance', to: 'attendance#add_attendance'
  root to: "games#index"

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'

  resources :qr_codes, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :ticket

  enum status: {
    absent: 0,
    entered: 1
  }
end

app/models/competition.rb
class Competition < ApplicationRecord
  has_many :team_competitions
  has_many :teams, through: :team_competitions
  has_many :games, dependent: :destroy
  has_many :week_tables, dependent: :destroy

  after_save :save_team_competition

  def save_team_competition
    Team.all.each do |team|
      TeamCompetition.create!(team: team, competition: self, points: 0)
    end
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  # makes Current.user accessible in view files.
  attribute :user
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :team_one_id, class_name: "Team", foreign_key: "team_one_id"
  belongs_to :team_two_id, class_name: "Team", foreign_key: "team_two_id"
  belongs_to :competition

  after_save :save_week_table

  after_destroy :delete_from_week_table

  def save_week_table
    save_team_one_record
    save_team_two_record
  end

  def delete_from_week_table
    delete_team_one_record
    delete_team_two_record
  end

  def save_team_one_record
    if team_one_score > team_two_score
      points = 3
      result = :win
    elsif team_one_score == team_two_score
      points = 1
      result = :draw
    else
      points = 0
      result = :lost
    end
    current_week_game = Game.where("game_number = ?", game_number)
    match_played = current_week_game.where("(games.team_one_id = ? AND games.team_two_id = ?) OR
(games.team_two_id = ? AND games.team_one_id = ?)", team_one_id, team_two_id, team_one_id, team_two_id)

    week_table = WeekTable.find_by("created_at >= ?", self.created_at)
    if week_table.nil?
      WeekTable.create!(team: team_one_id, points: points, goal_for: team_one_score, goal_against: team_two_score,
                        goal_diff: (team_one_score - team_two_score), match_played: match_played.count, result: result,
                        competition_id: competition_id)
    else
      week_table.update!(team: team_one_id, points: points, goal_for: team_one_score, goal_against: team_two_score,
                         goal_diff: (team_one_score - team_two_score), match_played: match_played.count, result: result,
                         competition_id: competition_id)
    end
    team_competition = TeamCompetition.find_by(team_id: team_one_id, competition_id: competition_id)
    team_competition_pts = team_competition.points.to_i + points
    team_competition.update!(points: team_competition_pts)
  end

  def save_team_two_record
    if team_two_score > team_one_score
      points = 3
      result = :win
    elsif team_two_score == team_one_score
      points = 1
      result = :draw
    else
      points = 0
      result = :lost
    end
    current_week_game = Game.where("game_number = ?", game_number)
    match_played = current_week_game.where("(games.team_one_id = ? AND games.team_two_id = ?) OR
(games.team_two_id = ? AND games.team_one_id = ?)", team_one_id, team_two_id, team_one_id, team_two_id)

    week_table = WeekTable.find_by("created_at >= ?", self.created_at)
    if week_table.nil?
      WeekTable.create!(team: team_two_id, points: points, goal_for: team_two_score, goal_against: team_one_score,
                        goal_diff: (team_two_score - team_one_score), match_played: match_played.count, result: result,
                        competition_id: competition_id)
    else
      week_table.update!(team: team_two_id, points: points, goal_for: team_two_score, goal_against: team_one_score,
                         goal_diff: (team_two_score - team_one_score), match_played: match_played.count, result: result,
                         competition_id: competition_id)
    end

    team_competition = TeamCompetition.find_by(team_id: team_two_id, competition_id: competition_id)
    team_competition_pts = team_competition.points.to_i + points
    team_competition.update!(points: team_competition_pts)
  end

  def delete_team_one_record
    week_table = WeekTable.find_by("created_at >= ?", self.created_at)
    week_table.destroy!

    if team_one_score > team_two_score
      points = 3
    elsif team_one_score == team_two_score
      points = 1
    else
      points = 0
    end

    team_competition = TeamCompetition.find_by(team_id: team_one_id, competition_id: competition_id)
    team_competition_pts = team_competition.points.to_i - points
    team_competition.update!(points: team_competition_pts)
  end

  def delete_team_two_record
    week_table = WeekTable.find_by("created_at >= ?", self.created_at)
    week_table.destroy!

    if team_two_score > team_one_score
      points = 3
    elsif team_two_score == team_one_score
      points = 1
    else
      points = 0
    end

    team_competition = TeamCompetition.find_by(team_id: team_two_id, competition_id: competition_id)
    team_competition_pts = team_competition.points.to_i - points
    team_competition.update!(points: team_competition_pts)
  end

  def current_week_game
    Game.where("game_number = ?", game_number)
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  include Drivers::Email
  include EmailValidatable

  has_many :tickets, dependent: :destroy
  enum status: {
    pending: 0,
    approved: 1
  }

  validates_presence_of :full_name, :email, :e_transfer_number
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }

  after_update :send_eticket_email, if: :approved?

  def send_eticket_email
    ticket_email(self)
  end
end

app/models/player.rb
class Player < ApplicationRecord
  include ImageUploader::Attachment(:image)
  belongs_to :team
  validates :name, presence: true

  enum player_role: {
    captain: 0,
    vice_captain: 1,
    player: 2
  }
end

app/models/qr_code.rb
class QrCode < ApplicationRecord

end

app/models/team.rb
class Team < ApplicationRecord
  include ImageUploader::Attachment(:logo)
  validates :name, presence: true

  has_many :players, dependent: :destroy
  has_many :week_tables, dependent: :destroy
  has_many :team_competitions
  has_many :competitions, through: :team_competitions
end

app/models/team_competition.rb
class TeamCompetition < ApplicationRecord
  belongs_to :team
  belongs_to :competition
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :participant

  has_one :attendance, dependent: :destroy

  enum age_group: {
    children: 0,
    adult: 1
  }
end

app/models/user.rb
class User < ApplicationRecord
  # adds virtual attributes for authentication
  has_secure_password
  # validates email
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
end

app/models/week_table.rb
class WeekTable < ApplicationRecord
  belongs_to :team
  belongs_to :competition
  enum result: {
    lost: 0,
    draw: 1,
    win: 2
  }
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/home/index.html.erb
<h1>QR Code Reader on Rails with Zxing-js</h1>

<ul>
  <li><%= link_to 'Basic QR Code Reader', basic_qr_code_reader_path %></li>
  <li><%= link_to 'QR Code Reader connected to a Rails controller and model', qr_codes_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QrCodeReaderDemo</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
  <style>

  </style>
</head>

<body>

<div class="container">
<!--  <div class="columns">-->
<!--    <div class="column">-->
<!--      <img src="https://thedrukcanada.com/img/dc_logo.jpeg" alt="Druk Canada" width="140" height="80">-->
<!--      <span style="position: relative; bottom: 60px; padding-right: 0px;">-->
        <%# if Current.user %>
          <%#= link_to 'Participants', participants_path %>
<!--          &nbsp;&nbsp;|&nbsp;&nbsp;-->
          <%#= link_to 'Scan Ticket', basic_qr_code_reader_path %>
<!--          &nbsp;&nbsp;|&nbsp;&nbsp;-->
<!--          Logged in as: <%#= Current.user.email %><br/>-->
          <%#= button_to 'Logout', logout_path, method: :delete %>
        <%# else %>
          <%#= link_to 'Login', sign_in_path %>
        <%# end %>
<!--      </span>-->
<!--    </div>-->
<!--  </div>-->

  <% if notice.present? %>
    <div class="notice notification is-success" style="text-align: center; color: #ffffff; font-size: 16px" id="validateNotice">
      <%= notice %>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="notice notification is-danger" style="text-align: center; color: #ffffff; font-size: 16px" id="validate">
      <%= alert %>
    </div>
  <% end %>

  <br/><br/><br/><br/>
  <%= yield %>
</div>
<script>
    $('#validate').fadeIn(1000);
    setTimeout(function () {
        $('#validate').fadeOut(1000);
    }, 2000);

    $('#validateNotice').fadeIn(1000);
    setTimeout(function () {
        $('#validateNotice').fadeOut(1000);
    }, 2000);
</script>
</body>
</html>