config/routes.rb
Rails.application.routes.draw do
  resources :competitions
  resources :games
  resources :players
  resources :teams
  get 'guests/new'
  resources :participants
  resources :guests
  resources :attendance
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'basic-qr-code-reader', to: 'basic_qr_codes#index'
  post 'attendance', to: 'attendance#add_attendance'
  root to: "games#index"

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'

  resources :qr_codes, only: [:new, :create, :show]
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :team_one_id, class_name: "Team", foreign_key: "team_one_id"
  belongs_to :team_two_id, class_name: "Team", foreign_key: "team_two_id"
  belongs_to :competition

  after_save :save_week_table

  after_destroy :delete_from_week_table

  def save_week_table
    save_team_one_record
    save_team_two_record
  end

  def delete_from_week_table
    delete_team_one_record
    delete_team_two_record
  end

  def save_team_one_record
    if team_one_score > team_two_score
      points = 3
      result = :win
    elsif team_one_score == team_two_score
      points = 1
      result = :draw
    else
      points = 0
      result = :lost
    end
    current_week_game = Game.where("game_number = ?", game_number)
    match_played = current_week_game.where("(games.team_one_id = ? AND games.team_two_id = ?) OR
(games.team_two_id = ? AND games.team_one_id = ?)", team_one_id, team_two_id, team_one_id, team_two_id)

    week_table = WeekTable.find_by("created_at >= ?", self.created_at)
    if week_table.nil?
      WeekTable.create!(team: team_one_id, points: points, goal_for: team_one_score, goal_against: team_two_score,
                        goal_diff: (team_one_score - team_two_score), match_played: match_played.count, result: result,
                        competition_id: competition_id)
    else
      week_table.update!(team: team_one_id, points: points, goal_for: team_one_score, goal_against: team_two_score,
                         goal_diff: (team_one_score - team_two_score), match_played: match_played.count, result: result,
                         competition_id: competition_id)
    end
    team_competition = TeamCompetition.find_by(team_id: team_one_id, competition_id: competition_id)
    team_competition_pts = team_competition.points.to_i + points
    team_competition.update!(points: team_competition_pts)
  end

  def save_team_two_record
    if team_two_score > team_one_score
      points = 3
      result = :win
    elsif team_two_score == team_one_score
      points = 1
      result = :draw
    else
      points = 0
      result = :lost
    end
    current_week_game = Game.where("game_number = ?", game_number)
    match_played = current_week_game.where("(games.team_one_id = ? AND games.team_two_id = ?) OR
(games.team_two_id = ? AND games.team_one_id = ?)", team_one_id, team_two_id, team_one_id, team_two_id)

    week_table = WeekTable.find_by("created_at >= ?", self.created_at)
    if week_table.nil?
      WeekTable.create!(team: team_two_id, points: points, goal_for: team_two_score, goal_against: team_one_score,
                        goal_diff: (team_two_score - team_one_score), match_played: match_played.count, result: result,
                        competition_id: competition_id)
    else
      week_table.update!(team: team_two_id, points: points, goal_for: team_two_score, goal_against: team_one_score,
                         goal_diff: (team_two_score - team_one_score), match_played: match_played.count, result: result,
                         competition_id: competition_id)
    end

    team_competition = TeamCompetition.find_by(team_id: team_two_id, competition_id: competition_id)
    team_competition_pts = team_competition.points.to_i + points
    team_competition.update!(points: team_competition_pts)
  end

  def delete_team_one_record
    week_table = WeekTable.find_by("created_at >= ?", self.created_at)
    week_table.destroy!

    if team_one_score > team_two_score
      points = 3
    elsif team_one_score == team_two_score
      points = 1
    else
      points = 0
    end

    team_competition = TeamCompetition.find_by(team_id: team_one_id, competition_id: competition_id)
    team_competition_pts = team_competition.points.to_i - points
    team_competition.update!(points: team_competition_pts)
  end

  def delete_team_two_record
    week_table = WeekTable.find_by("created_at >= ?", self.created_at)
    week_table.destroy!

    if team_two_score > team_one_score
      points = 3
    elsif team_two_score == team_one_score
      points = 1
    else
      points = 0
    end

    team_competition = TeamCompetition.find_by(team_id: team_two_id, competition_id: competition_id)
    team_competition_pts = team_competition.points.to_i - points
    team_competition.update!(points: team_competition_pts)
  end

  def current_week_game
    Game.where("game_number = ?", game_number)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create

    return same_team_error if game_params['team_one_id'] == game_params['team_two_id']

    return invalid_game if game_params['game_number'].to_i > 15

    new_params = { team_one_id: Team.find(game_params['team_one_id']),
                   team_two_id: Team.find(game_params['team_two_id']),
                   team_one_score: game_params['team_one_score'],
                   team_two_score: game_params['team_two_score'],
                   competition_id: game_params['competition_id'],
                   game_number: game_params['game_number'] }

    @game = Game.new(new_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def same_team_error
    redirect_to new_game_url, alert: "Please select different teams"
  end

  def invalid_game
    redirect_to games_url, alert: "No more games can be played this game week"
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      new_params = { team_one_id: Team.find(game_params['team_one_id']),
                     team_two_id: Team.find(game_params['team_two_id']),
                     team_one_score: game_params['team_one_score'],
                     team_two_score: game_params['team_two_score'],
                     competition_id: game_params['competition_id'],
                     game_number: game_params['game_number'] }

      if @game.update(new_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:team_one_id, :team_two_id, :team_one_score, :team_two_score, :competition_id, :game_number)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h1 style="font-weight: bold; padding-top: 20%; padding-bottom: 5%;">
    <%= Competition.last.name %>
    <%= form.hidden_field :competition_id, value: Competition.last.id %>
  </h1>

  <div class="field">
    <div class="select is-primary">
      <%= form.collection_select :team_one_id, Team.order(:name), :id, :name, style: "width: 100%" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :team_one_score, class: 'label' %>
    <div class="control">
      <%= form.number_field :team_one_score, required: true, class: 'input' %>
    </div>
  </div>

  <h1 style="font-weight: bold; text-align: center; font-size: 30px">Vs.</h1>
  <br/>

  <div class="field">
    <div class="select is-primary">
      <%= form.collection_select :team_two_id, Team.order(:name), :id, :name %>
    </div>
  </div>

  <div class="field">
    <%= form.label :team_two_score, class: 'label' %>
    <div class="control">
      <%= form.number_field :team_two_score, required: true, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <% game_num = Game.where(competition_id: Competition.last.id).order(:game_number)&.last&.game_number.to_i %>
    <%= form.label :game_number, class: 'label' %>
    <div class="control">
      <%= form.number_field :game_number, class: 'input', value: "#{game_num + 1}" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-success" %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<% game = @game %>
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h1 style="font-weight: bold; padding-top: 20%; padding-bottom: 5%;">
    <%= Competition.last.name %>
    <%= form.hidden_field :competition_id, value: Competition.last.id %>
  </h1>

  <div class="field">
    <div class="select is-primary">
      <%= form.collection_select :team_one_id, Team.all, :id, :name, { :selected => game.team_one_id }, style: "width: 100%" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :team_one_score, class: 'label' %>
    <div class="control">
      <%= form.number_field :team_one_score, required: true, class: 'input' %>
    </div>
  </div>

  <h1 style="font-weight: bold; text-align: center; font-size: 30px">Vs.</h1>
  <br/>

  <div class="field">
    <div class="select is-primary">
      <%= form.collection_select :team_two_id, Team.all, :id, :name, { :selected => game.team_two_id } %>
    </div>
  </div>

  <div class="field">
    <%= form.label :team_two_score, class: 'label' %>
    <div class="control">
      <%= form.number_field :team_two_score, required: true, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <% game_num = Game.where(competition_id: Competition.last.id)&.last&.game_number.to_i %>
    <%= form.label :game_number, class: 'label' %>
    <div class="control">
      <%= form.number_field :game_number, class: 'input'%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-success" %>
  </div>
<% end %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="font-weight: bold">SEASON TABLE</h1>
<br/>

<table class="table is-striped">
  <thead>
  <tr>
    <th>Team</th>
    <th>Points</th>
  </tr>
  </thead>

  <tbody>
  <% TeamCompetition.where(competition_id: Competition.last).order('points desc').each do |team_competition| %>
    <% team = team_competition.team %>
    <tr>
      <td><a href="<%= team_path(team.id) %>"><%= team.name %></a></td>
      <td><%= TeamCompetition.where(team: team).sum(:points).to_i || 0 %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br/>

<h1 style="font-weight: bold">GAMES OF THE WEEK</h1>
<br/>

<table class="table is-striped">
  <thead>
  <tr>
    <th>Team one</th>
    <th>Team two</th>
    <th>Team one score</th>
    <th>Team two score</th>
    <th>Game number</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @games.where(competition_id: Competition.last.id).order(:game_number).each do |game| %>
    <tr>
      <td><a href="<%= team_path(game.team_one_id.id) %>"><%= game.team_one_id.name %></a></td>
      <td><a href="<%= team_path(game.team_two_id.id) %>"><%= game.team_two_id.name %></a></td>
      <td><%= game.team_one_score %></td>
      <td><%= game.team_two_score %></td>
      <td><%= game.game_number %></td>
      <td><%= link_to 'Show', game %></td>
      <td><%= link_to 'Edit', edit_game_path(game) %></td>
      <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New Game', new_game_path, class: "button is-success" %>

<br/><br/><br/><br/>
<h1 style="font-weight: bold">WEEK TABLE</h1>
<br/>

<table class="table is-striped">
  <thead>
  <tr>
    <th>Team</th>
    <th>Match Played</th>
    <th>Wins</th>
    <th>Lost</th>
    <th>Draw</th>
    <th>Points</th>
    <th>GF</th>
    <th>GA</th>
    <th>GD</th>
  </tr>
  </thead>

  <tbody>
  <% TeamCompetition.where(competition_id: Competition.last).order('points desc').each do |team_competition| %>
    <% team = team_competition.team %>
    <% week_table = WeekTable.where(team: team, competition: Competition.last) %>
    <tr>
      <td><a href="<%= team_path(team.id) %>"><%= team.name %></a></td>
      <td><%= week_table.count || 0 %></td>
      <td><%= week_table.where(result: :win).count || 0 %></td>
      <td><%= week_table.where(result: :lost).count || 0 %></td>
      <td><%= week_table.where(result: :draw).count || 0 %></td>
      <td><%= week_table.sum(:points) || 0 %></td>
      <td><%= week_table.sum(:goal_for) || 0 %></td>
      <td><%= week_table.sum(:goal_against) || 0 %></td>
      <td><%= week_table.sum(:goal_diff) || 0 %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br/><br/><br/><br/><br/><br/>

app/views/games/new.html.erb
<div id="stopwatch">
  00:00:00
</div>

<ul id="buttons">
  <li><button onclick="startTimer()">Start</button></li>
  <li><button onclick="stopTimer()">Stop</button></li>

  <li><button onclick="resetTimer()">Reset</button></li>
</ul>

<div class="columns">
  <div class="column"></div>
  <div class="column">
    <%= render 'form', game: @game %>
    <br/><br/>
    <%= link_to 'Back', games_path %>
  </div>
  <div class="column"></div>
</div>


<script>
    const timer = document.getElementById('stopwatch');

    var hr = 0;
    var min = 0;
    var sec = 0;
    var stoptime = true;

    function startTimer() {
        if (stoptime == true) {
            stoptime = false;
            timerCycle();
        }
    }
    function stopTimer() {
        if (stoptime == false) {
            stoptime = true;
        }
    }

    function timerCycle() {
        if (stoptime == false) {
            sec = parseInt(sec);
            min = parseInt(min);
            hr = parseInt(hr);

            sec = sec + 1;

            if (sec == 60) {
                min = min + 1;
                sec = 0;
            }
            if (min == 60) {
                hr = hr + 1;
                min = 0;
                sec = 0;
            }

            if (sec < 10 || sec == 0) {
                sec = '0' + sec;
            }
            if (min < 10 || min == 0) {
                min = '0' + min;
            }
            if (hr < 10 || hr == 0) {
                hr = '0' + hr;
            }

            timer.innerHTML = hr + ':' + min + ':' + sec;

            setTimeout("timerCycle()", 1000);
        }
    }

    function resetTimer() {
        timer.innerHTML = "00:00:00";
        stoptime = true;
        hr = 0;
        sec = 0;
        min = 0;
    }
</script>

<style>
    button {
        width: 100px;
        height: 30px;
        border: 3px soldi white;
        border-radius: 50px;
        background: #202020;
        color: white;
        cursor: pointer;
        outline: none;
    }

    #stopwatch {
        font-size: 100px;
        position: absolute;
        top: 10%;
        left: 50%;
        transform: translate(-50%, -55%);
    }
    #buttons {
        position: absolute;
        top: 20%;
        left: 48.4%;
        transform: translate(-51.6%, -45%);
    }
    #buttons li {
        display: inline;
        padding-left: 10px;
    }
</style>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team one:</strong>
  <%= @game.team_one_id.name %>
</p>

<p>
  <strong>Team two:</strong>
  <%= @game.team_two_id.name %>
</p>

<p>
  <strong>Team one score:</strong>
  <%= @game.team_one_score %>
</p>

<p>
  <strong>Team two score:</strong>
  <%= @game.team_two_score %>
</p>

<p>
  <strong>Game week:</strong>
  <%= @game.game_week %>
</p>

<p>
  <strong>Game number:</strong>
  <%= @game.game_number %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>